global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['monitoring-alertmanager:9093']

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'collectionserver-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['collectionserver-api:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['monitoring-prometheus:9090']
